### ISSUE TITLE
need your help in a programming issue

### ISSUE THREAD

**Issue by fatememir** [netgfx/ReactNative-Showcase#34]
hello . i saw your comment in just_audio flutter github . you commented in  an issue in implementation this plugin in web.
[https://github.com/ryanheise/just_audio/issues/611](url)
 i have a problem in web and i searched a lot but i cant find solution . could you help me?
if you implemented this plugin before,please send me example codes
i can send you the repository and screen shot for bug. thank you

**Comment by netgfx** [comment]
@fatememir Hello, then how come you didn't ping me on that issue, but instead you are commenting on a totally different repository...
If you want some help with just_audio send me an email at contact@netgfx.com

**Comment by fatememir** [comment]
> [contact@netgfx.com](mailto:contact@netgfx.com)

I sended you an email ,thank you
